#!/usr/bin/python2
"""Usage:
    pymoticz list [--host]
    pymoticz test
    pymoticz status <id> [--host]
    pymoticz on <id> [--host]
    pymoticz off <id> [--host]
    pymoticz dim <id> <level> [--host]
"""
import sys
from docopt import docopt
from __init__ import Pymoticz
from pprint import pprint

if __name__ == '__main__':
    args=docopt(__doc__)

    if args['list']:
        p=Pymoticz()
        response = p.list()
        print response
    elif args['status']:
        p=Pymoticz()
        response = p.get_light_status(args['<id>'])
        print(response)
    elif args['on']:
        p=Pymoticz()
        response = p.turn_on(args['<id>'])
    elif args['off']:
        p=Pymoticz()
        response = p.turn_off(args['<id>'])
    elif args['dim']:
        p=Pymoticz()
        response = p.dim(args['<id>'], args['<level>'])
        pprint(response)

